### ISSUE TITLE
ValueError when getting MicrosoftAuthenticatedUser

### ISSUE THREAD

**Issue by 15Ibans** [Lucino772/pymojang#71]
I bought an alt account around a week ago, and whenever I try to authenticate this account I'm getting a ValueError about an incorrect time format. It seems to only occur with this account, since I've tried another alt and it works just fine. Below is the stacktrace.

```Traceback (most recent call last):
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/general/skin-recolor-auto/main.py", line 232, in index
    sess = auth_app.get_session(request.args["code"])
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/auth/models.py", line 341, in get_session
    return MicrosoftAuthenticatedUser(
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/auth/models.py", line 212, in __init__
    super().__init__(access_token, refresh_token)
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/auth/models.py", line 52, in __init__
    self._fetch_profile()
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/auth/models.py", line 128, in _fetch_profile
    name_change = session.get_user_name_change(self._access_token)
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/session.py", line 121, in get_user_name_change
    data["created_at"] = dt.datetime.strptime(
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-03-15T15:46:59.326185Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by Lucino772** [comment]
Thank you for opening an issue, I'll look into it.
