### ISSUE TITLE
Exception when changing skin using local file

### ISSUE THREAD

**Issue by 15Ibans** [Lucino772/pymojang#73]
When calling the change_skin method from MicrosoftAuthenticatedUser and passing in a local skin file as the path, I'm getting a ValueError. Below is the trace.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/general/skin-recolor-auto/main.py", line 283, in run
    upload_random_skin(sess)
  File "/home/general/skin-recolor-auto/main.py", line 205, in upload_random_skin
    session.change_skin(path=skin_file, variant="classic")
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/auth/models.py", line 143, in change_skin
    session.change_user_skin(self._access_token, path, variant)
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/session.py", line 182, in change_user_skin
    code, _ = helpers.err_check(
  File "/home/general/skin-recolor-auto/venv/lib/python3.9/site-packages/mojang/api/helpers.py", line 38, in err_check
    raise exception(response.text)
ValueError: {
  "path" : "/minecraft/profile/skins",
  "errorMessage" : "variant is marked non-null but is null"
}
```

**Comment by Lucino772** [comment]
Thank you for opening an issue, I'll look into it.
